image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - test

before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose


test:
  stage: test
  tags:
    - test
  script:
    - docker-compose -f docker-compose.prod.yml up -d db test_web test_frontend
  only:
    - master
    - develop

