stages:
  - test

before_script:
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose


test:
  stage: test
  tags:
    - test
  script:
    - docker-compose -f docker-compose.prod.yml up -d db test_web test_frontend
  only:
    - master
    - develop

