version: '3.3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}

  web:
    build: 
      context: .
      dockerfile: ./docker/back/Dockerfile
    container_name: backend_app
    restart: unless-stopped
    env_file:
      - ./docker/back/backend.env
    volumes: 
      - ./ACN_backend_service:/app
    command: ./scripts/run.sh
    network_mode: host
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes: 
      - ./ACN_frontend_service:/app
    command: npm start
    network_mode: host

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    volumes:
      - ./ACN_backend_service:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yml
