version: '3.3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: 
      context: .
      dockerfile: ./docker/back/Dockerfile
    container_name: backend_app
    restart: unless-stopped
    env_file:
      - ./docker/back/backend.env
    volumes: 
      - ./ACN_backend_service
    command: ./scripts/run.sh
    network_mode: host
    depends_on:
      - db
  
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    volumes:
      - ./ACN_backend_service:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yml
