FROM node:14-alpine
WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
RUN npm install -g create-react-app
RUN npm install -g serve
COPY . /app
RUN npm run build
CMD serve -s build -l 3000
EXPOSE 3000
